### ISSUE TITLE
[2.25] [minor] Boris intro dialog is cut

### ISSUE THREAD

**Issue by nashounet** [tchegito/zildo#94]
Boris, the alchemist on Fishermen's Island, can't even explain the subquest for cheap dynamite if you get an empty bag form Bilel before talking to him.

**Comment by tchegito** [comment]
Fixed in 2.29

Actually there was 2 problems:
- init sentence was cut, as it's stated here (3 sentences instead of 1)
- dynamite subquest wasn't explained before looking any bag possession

Second problem was about the switch script of Boris:
init:0,itemEMPTY_BAG&!itemFULL_BAG&!giveSawdust:5,itemFULL_BAG&!giveSawdust:6,giveSawdust&!borisWait:7,borisWait:8,igorAsk:3,0

So I introduced a new quest, triggered when Boris talks about Igor. That means, if hero never met Igor, he won't obtain any dynamite from Boris.

ad9cafdc92cf0318a7f604c366afa378bb7580ad
